#ifndef ERROR_MANAGER_H
#define ERROR_MANAGER_H

#define bool int
#define false 0
#define true 1

#define ERROR_SALA_ABIERTA -10
#define ERROR_SALA_CERRADA -11
#define ERROR_SALA_LLENA -12
#define ERROR_ID_ASIENTO -13
#define ERROR_ID_PERSONA -14
#define ERROR_ASIENTO_VACIO -15
#define ERROR_SALA_CAPACIDAD -16
#define ERROR_MEMORIA -17
#define ERROR_FICHERO_OPEN -18
#define ERROR_FICHERO_WRITE -19
#define ERROR_FICHERO_READ -20
#define ERROR_FICHERO_CLOSE -21
#define ERROR_FICHERO_LSEEK -22


#endif